pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm run test'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Dockerize Frontend') {
            steps {
                sh 'docker build -t frontend-app .'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker tag frontend-app <AWS_ECR_URL>/frontend-app'
                sh 'docker push <AWS_ECR_URL>/frontend-app'
            }
        }
    }
}