pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'python manage.py test'
            }
        }

        stage('Dockerize Backend') {
            steps {
                sh 'docker build -t backend-app .'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker tag backend-app <AWS_ECR_URL>/backend-app'
                sh 'docker push <AWS_ECR_URL>/backend-app'
            }
        }
    }
}
