# Generated by Django 5.1.4 on 2024-12-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nom',
            new_name='nommm',
        ),
    ]
