# Generated by Django 5.1.4 on 2025-01-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_user_is_active_user_is_staff_user_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mdp',
        ),
    ]
