# Generated by Django 5.1.4 on 2025-02-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_question_entretien_remove_rapport_entretien_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='audio_file',
            field=models.FileField(default=0, upload_to='audio_answers/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
