# Generated by Django 5.1.4 on 2025-02-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_answer_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(default=0, upload_to='audio_questions/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='audio_file',
            field=models.FileField(upload_to='audio_answers/'),
        ),
    ]
